# Numpy

# 常用数组的创建

In [1]:
import numpy as np

##### numpy.empty(shape, dtype=float, order='c')

In [2]:
x1 = np.empty([3,2])

In [3]:
x1


array([[0., 0.],
       [0., 0.],
       [0., 0.]])

##### numpy.zeros(shape, dtype = float, order = 'C')

In [4]:
x2 = np.zeros([3,2])

In [5]:
x2

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

##### numpy.ones(shape, dtype = None, order = 'C') 

In [6]:
x3 = np.ones([3,2])

In [7]:
x3

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [8]:
x4 = np.random.random([3,2])

In [9]:
x4

array([[0.80460501, 0.7386248 ],
       [0.88829308, 0.67238694],
       [0.16567434, 0.96108784]])

## 常用数组操作 

##### reshape 不改变数据的情况下改变数组的形状
##### ndarray.flatten(order='C')

In [12]:
x5 = np.arange(12)

In [13]:
x5

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [17]:
x5.reshape(3, -1)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

##### flatten 返回一个数据展开后的拷贝，但不改变原本数组
##### ndarray.flatten(order='C')

In [18]:
x6 = np.arange(9).reshape(3,3)

In [19]:
x6

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [20]:
x6.flatten()

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [21]:
x6

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

##### 数组的转置
##### numpy.transpose(arr, axes)
##### numpy.ndarray.T

In [22]:
x7 = np.arange(12).reshape(3,4)

In [23]:
x7

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [24]:
np.transpose(x7)

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [27]:
x7.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

##### 数组的连接 
##### numpy.stack(arrays, axis)

In [28]:
x8 = np.array([[1,2],[3,4]])
x9 = np.array([[5,6],[7,8]])

In [29]:
np.stack((x8,x9),0) # 沿轴0堆叠两个数组

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [30]:
np.stack((x8,x9),1) # 沿轴1堆叠两个数组

array([[[1, 2],
        [5, 6]],

       [[3, 4],
        [7, 8]]])

##### numpy.vstack是numpy.stack的变体，通过水平堆叠来生成数组
##### numpy.hstack也是numpy.stack的变体，通过垂直堆叠来生产数组

In [31]:
np.vstack((x8,x9))

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [32]:
np.hstack((x8,x9))

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

## 线性代数
##### NumPy 提供了线性代数函数库 linalg，该库包含了线性代数所需的所有功能
##### numpy.dot(a, b, out=None) 两个数组的点积，即元素对应相乘。

In [25]:
x10 = np.array([[1,2],[3,4]])
x11 = np.array([[11,12],[13,14]])
np.dot(x10,x11)
# [[1*11+2*13, 1*12+2*14],[3*11+4*13, 3*12+4*14]]

array([[37, 40],
       [85, 92]])

##### numpy.vdot() 函数是两个向量的点积 

In [37]:
np.vdot(x10,x11)
# 1*11 + 2*12 + 3*13 + 4*14 = 130

130

##### numpy.inner() 函数返回一维数组的向量内积 

In [38]:
np.inner(np.array([1,2,3]),np.array([0,1,0]))
# 等同于先转置再点积
# 1*0+2*1+3*0

2

##### numpy.matmul 函数返回两个数组的矩阵乘积 

In [26]:
x12 = [[1,0],[0,1]] 
x13 = [[4,1],[2,2]] 
np.matmul(x12,x13)

array([[4, 1],
       [2, 2]])

In [28]:
x12 = np.array(x12)
x13 = np.array(x13)
x12 @ x13

array([[4, 1],
       [2, 2]])

##### numpy.linalg.inv() 函数计算矩阵的乘法逆矩阵 

In [29]:
np.linalg.inv(np.array([[1,2],[3,4]]))

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

##### numpy.linalg.det() 函数计算矩阵的行列式

In [30]:
np.linalg.det(np.array([[0,1],[2,3]]))

-2.0